---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: salarmgh
    group: salarmgh
    mode: "0755"
  with_items: "{{ dirs }}"

- name: Install dependencies
  pacman:
    name: "{{ pkgs }}"
    state: present
  become: true

- name: create user for aur
  user:
    name: aur_builder
    create_home: yes
    group: wheel
  become: true

- name: NOPASSWD for aur
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: "visudo -cf %s"
  become: true

- name: install aur packages
  aur:
    name: "{{ aur }}"
    state: present
  become: yes
  become_user: aur_builder

- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_packages }}"
  become: true
