---
- name: Copy configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: salarmgh
    group: salarmgh
    mode: "{{ item.perm }}"
  with_items: "{{ copy_files }}"

- name: Download vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/salarmgh/.vim/autoload/plug.vim
    mode: "0644"

- name: Install vim plugins
  command: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty

- name: Add user to groups
  user:
    name: salarmgh
    groups: "{{ item }}"
    append: yes
  become: true
  with_items: "{{ user_groups }}"

- name: Set timezone to Asia/Tehran
  timezone:
    name: Asia/Tehran
  become: true

- name: Enable NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes
  become: true

- name: Enable docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true
