---
- name: Copy configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: salarmgh
    group: salarmgh
    mode: "{{ item.perm }}"
  with_items: "{{ copy_files }}"

- name: Configure bashrc
  lineinfile:
    path: /home/salarmgh/.bashrc
    state: present
    line: |
      {{ bash_custom_config }}

- name: Download vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/salarmgh/.vim/autoload/plug.vim
    mode: "0644"

- name: Install vim plugins
  command: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty

- name: Add user to groups
  user:
    name: salarmgh
    groups: "{{ item }}"
    append: yes
  become: true
  with_items: "{{ user_groups }}"

- name: Set timezone to Asia/Tehran
  timezone:
    name: Asia/Tehran

- name: On-Screen keyboard height
  command: gsettings set org.onboard.window.landscape dock-height 405

- name: Disable terminal tabs
  command: gsettings set io.elementary.terminal.settings tab-bar-behavior 'Hide When Single Tab'

- name: Terminal font size
  command: gsettings set io.elementary.terminal.settings font 'Roboto Mono 13'
