---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: salarmgh
    group: salarmgh
    mode: "0755"
  with_items: "{{ dirs }}"

- name: apt proxy configuration
  copy:
    dest: /etc/apt/apt.conf.d/00proxy
    content: |
      Acquire::http::Proxy "{{ proxy }}";
      Acquire::https::Proxy "{{ proxy }}";
  become: true

- name: Add repo keys
  apt_key:
    url: "{{ item.repo_key }}"
    state: present
  with_items: "{{ repos }}"
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  become: true

- name: add repos
  apt_repository:
    repo: "{{ item.repo_url }}"
    state: present
  with_items: "{{ repos }}"
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  become: true

- name: add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ ppas }}"
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  become: true

- name: Install dependencies
  apt:
    name: "{{ pkgs }}"
    state: present
  become: true

- name: Check if debs installed
  command: "dpkg -s {{ item.name }}"
  register: debs_check
  with_items: "{{ debs }}"
  ignore_errors: yes

- name: Install debs
  apt:
    deb: "{{ item.url }}"
  with_items: "{{ debs }}"
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  become: true
  when: debs_check.rc == 1

- name: Install firmwares
  apt:
    name: "{{ firmware_pkgs }}"
    state: present
  become: true

- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items: "{{ npm_packages }}"
  become: true
