---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: salarmgh
    group: salarmgh
    mode: '0755'
  with_items: "{{ dirs }}"

- name: Install dependencies
  apt:
    name: "{{ pkgs }}"
    state: present
  become: true

- name: Install firmwares
  apt:
    name: "{{ firmware_pkgs }}"
    state: present
  become: true
